name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean package

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Maven wrapper
        run: chmod +x ./mvnw

      - name: Start Tomcat using Docker
        run: docker run -d -p 8080:8080 -e TOMCAT_USER=${{ secrets.TOMCAT_USERNAME }} -e TOMCAT_PASSWORD=${{ secrets.TOMCAT_PASSWORD }} tomcat:9.0

      - name: Wait for Tomcat to start
        run: sleep 20

      - name: Deploy to Tomcat
        run: ./mvnw org.apache.tomcat.maven:tomcat7-maven-plugin:2.2:deploy
        env:
          TOMCAT_USERNAME: ${{ secrets.TOMCAT_USERNAME }}
          TOMCAT_PASSWORD: ${{ secrets.TOMCAT_PASSWORD }}
          TOMCAT_URL: http://localhost:8080/manager/text
